from typing import Literal
from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.yaml"

from snakehelp import parameters


@parameters
class GenomeBuild:
    genome_build: str = "sacCer3"

@parameters
class Individual:
    genome_build: GenomeBuild
    individual: str = "simulated"


@parameters
class SingleHaplotypeAndChromosomeHifiReads:
    individual: Individual
    depth: int
    chromosome: str
    haplotype: Literal[0, 1]


@parameters
class HifiReads:
    individual: Individual
    dataset_size: Literal["small", "medium", "big"]
    depth: int


@parameters
class HiCReads:
    individual: Individual
    dataset_size: Literal["small", "medium", "big"]
    hic: Literal["hic"]
    n_reads: int = 100


@parameters
class HifiasmResults:
    individual: Individual
    dataset_size: Literal["small", "medium", "big"]
    depth: int
    n_reads: int


@parameters
class ScaffoldingResults:
    assembly_graph: HifiasmResults
    scaffolder: Literal["yahs", "custom"]



include: github("bioinf-benchmarking/mapping-benchmarking", "rules/reference_genome.smk", branch="master")
include: github("bioinf-benchmarking/mapping-benchmarking", "rules/read_simulation.smk", branch="master")
include: github("bioinf-benchmarking/mapping-benchmarking", "rules/mason.smk", branch="master")
include: "hifi_simulation.smk"
include: "hic_simulation.smk"
include: "hifiasm.smk"
include: "evaluation.smk"
include: "tests.smk"



